project:
  type: website
  output-dir: docs

website:
  title: "Qingyin Cai"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "RESEARCH"
        href: research.qmd      
      - text: "TEACHING"
        href: teaching.qmd
      - text: "CV"
        href: cv_2024_june.pdf

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: false



