
::: {.column-page}


## Job Market Paper
**Drought and Fresh Produce Production in California**
(with Metin Çakır and Timothy Beatty) <a href="JMP_Cai.pdf" target="_blank">[Link]</a>

Awarded the Jason Beddow Second-Year Paper Award (University of Minnesota, 2022)

<u>Abstract</u>: 

California's increasingly frequent and intense drought is a pressing problem for the state’s agriculture and the U.S. food supply, as the state is the major producer of many agricultural products. Particularly, California supplies more than half of all fruit and vegetables in the country. This paper examines the severity of the problem by estimating the impacts of the drought on California’s fresh fruit and vegetable production. We estimate panel data models using comprehensive, county-level agriculture, irrigation, and weather data from 2000 to 2019. Our findings indicate that droughts significantly reduce total output, ranging from 1.2\% to 2.2\% for each additional week of drought. The estimated effect is driven by lower yields and fewer harvested acres due to the drought. The drought effects also differ among crops, with thirsty crops and crops with lower economic returns and established insurance programs being disproportionately affected. Results also show the extent to which higher irrigation levels mitigate the adverse effects of drought. Our findings provide insights into the importance of enhancing drought-related risk management and implications for designing cost-effective policies for future adaptation decisions.

<u>Presentations</u>:

- 2025 AEA Allied Social Science Associations Annual Meeting (upcoming)  
- 2024 Department of Applied Economics Student Seminar (University of Minnesota)
- 2024 Canadian Agricultural Economics Society (CAES/SCAÉ) Annual Meeting (Winnipeg, Canada)
- 2022 Agricultural and Applied Economics Association Annual Meeting (Anaheim, CA)
- 2022 Food Group Seminar (University of Minnesota)


## Working Papers
<details><summary style="color: black;">**Does the Recent Food Price Inflation Differ by Store Format?** (with Metin Çakır and Megan Sweitzer) </summary> <u>Abstract</u>: Recent spikes in food prices have raised significant economic concerns in the United States. Understanding how food price inflation varies across store formats provides valuable insights into consumer behavior and the strategies retailers employ during economic downturns. In this study, we use retail scanner data to construct price indices by store format for various food product groups, allowing us to estimate differences in the rates of price changes across stores. We then estimate a structural store-choice model to examine how these differential rates of price changes affect consumers' preferences for different store formats. Our findings reveal that food price inflation rates vary significantly by store format, with nontraditional stores generally experiencing lower inflation rates than traditional stores across most food categories. These differential price changes also influence consumer store and product choices.</details>


<details><summary style="color: black;">**California Drought, Fresh Fruit and Vegetable Prices, and Consumer Welfare** (with Metin Çakır, Timothy Beatty, and Timothy Park) </summary> <u>Abstract</u>: California produces more than a third of all vegetables and two-thirds of all fruits and nuts in the United States and is the largest producer of over fifty fruits, vegetables, and tree nuts. Meanwhile, California agriculture faces important challenges due to sustained drought with increasing frequency and severity across the state since 2011. This article estimates the effect of the recent California drought on the retail prices of fresh fruits and vegetables (FFV) using panel data models. We build a dataset comprising detailed information on FFV prices and the drought. Specifically, we construct a monthly panel price index for fresh fruits and vegetables using retail scanner data and obtain California's county-level historical drought data from the United States Drought Monitor. In our estimation, we account for the heterogeneous effects of the drought across products and space. Our main finding is that the drought had a positive and significant effect on FFV prices. This effect is generally larger on fruits than vegetables and is robust to alternative measures of drought and model specifications. Furthermore, we find that the drought's impacts on production and imports are among the significant determinants of its overall effect on prices.</details>


 <details><summary style="color: black;">**Emotional Shocks and Consumer Spending** (with Qingxiao Li) </summary> <u>Abstract</u>: We examine the impact of emotional shocks on consumer spending behaviors by leveraging the unexpected outcomes of professional football games as a natural experiment. Using scanner data from consumers, we analyze changes in spending on food and alcohol in response to these emotional events. We compile a dataset that encompasses NFL regular seasons from 2004 to 2019 and link it with the purchase records of 83,755 households. Conditioning our analysis on the Las Vegas pregame point spread, we find that (i) unexpected losses by the home team lead to a significant increase in spending on food, particularly indulgent options, and alcohol; (ii) losses in closely contested games result in positive but smaller effects on consumer spending; (iii) unexpected wins by the home team lead to a reduction in spending, with a more pronounced effect compared to unexpected losses; and (iv) the effects of upset losses and wins on spending are more substantial during high-stakes games, early games, and among households with strong sports affiliations. Our results are further supported by various heterogeneity analyses and robustness checks. These findings enhance our understanding of individual responses to unexpected emotional shocks and provide evidence for the role of emotions in consumer behavior.</details>




<details><summary style="color: black;">**Moral Hazard in Agricultural Insurance - Evidence from Non-Voluntary Sow Insurance Program in China** (with Xudong Rao and Yuehua Zhang) *Conditionally accepted at Australian Journal of Agricultural and Resource Economics* </summary> <u>Abstract</u>: Agricultural insurance has not yet lived up to its full potential despite its apparent benefits to agricultural producers. Moral hazard is suspected to be a major obstacle to the adoption of agricultural insurance, especially livestock insurance. In this study, we take advantage of a government-supported, non-voluntary sow insurance program in China and examine whether farmers being aware of having insurance coverage leads to their hazardous behaviors. We estimate these impacts by using an endogenous treatment effects model which controls for endogeneity in our treatment variable. Our results are robust and suggest that farmers’ awareness of their insurance enrollment led to statistically and economically significant differences in their sow mortality rates. Therefore, our results demonstrate the presence of hazardous behavior.</details>



<details><summary style="color: black;">**How Importance is Junior High School Education Early in Life to Cognitive Outcomes of Elderlies: Evidence from A Quasi-Experiment in China** (with Wen You and Yuehua Zhang) *under review* </summary> <u>Abstract</u>: As an important part of mental health, cognitive outcomes play a vital role in the quality of life for older adults. Identifying potential early life factors that can influence cognitive outcomes at older ages is of great public health importance. We examine the impact of obtaining junior high education early in life on the cognitive abilities of elderly individuals using a wave of longitudinal data set, the China Health and Retirement Longitudinal Study. We leverage the Cultural Revolution of 1966-1968 as a quasi-experiment identification strategy since this political event almost completely closed down junior high schools in China and created exogenous shocks to the relevant generation’s junior high education experience. We employed the instrumental variable and regression discontinuity methods using this political event as an instrument and discontinuity threshold respectively. Empirical results show that respondents who successfully obtained junior high school education early in life showed higher scores on all cognitive tests in later life. This research further excavates the long-term impact of the Cultural Revolution and provides evidence to support junior high education completion policies and programs for children.</details>



## Work in Progress
**Extreme Weather Events and Farm Consolidation in the United States** (with Metin Çakır)

**Societal Preferences for Donation to Rare Diseases: A Discrete Choice Experiment** (with Wen Lin and Yuehua Zhang)


## Publication
**Qingyin Cai**, Yulian Ding, Calumn Turvey, and Yuehua Zhang (2021). "The Influence of Past Experience on Farmers’ Preferences for Hog Insurance Products: a Natural Experiment and Choice Experiment in China." *The Geneva Papers on Risk and Insurance - Issues and Practice*, 46: 399-421. [[Link]](https://link.springer.com/article/10.1057/s41288-021-00209-7)