
::: {.column-page}

## Instructor
**University of Minnesota** (Minnesota, United States)

- Graduate Course
  - Introduction to R Statistical Analysis Software: Summer 2025
    - [Lecture 0](Lec0.html)
    - [Lecture 1](Lec1.html)
    - [Lecture 2](Lec2.html)
    - [Lecture 3](Lec3.html)
    - [Lecture 4](Lec4.html); [Exercise](Lec4_exercise.html)
    - [Lecture 5](Lec5.html)
    


## Guest Lecturer

**University of Minnesota** (Minnesota, United States)

- Graduate Course
  - APEC 8803 Applied Consumer Theory: Fall 2024

**Institution Commercial Development International Business School** (Shanghai, China)

- Graduate Course
  - Welfare Economics: Fall 2020


## Teaching Assistant

**Zhejiang University** (Hangzhou, China)

- Graduate Course
  - Field Survey and Questionnaire Design: Spring 2019

- <span style="margin-top: 20px; display: block;"> Undergraduate Course 
  - Insurance Economics: Fall 2018
  - Social Insurance: Fall 2017, Spring 2020

## Mentor

**University of Minnesota** (Minnesota, United States)

- Incoming Ph.D. Student Mentor, Deparment of Applied Economcis: 2022-2024

